### ISSUE TITLE
RSS not updated since March 21, 2024

### ISSUE THREAD

**Issue by dwincort** [smbc-rss-plus/smbc-rss-plus#31]
It looks like the actions stopped 3 weeks ago.

Also, just wanted to say that I've used this for years and really appreciate your maintenance work on it.  Thanks!

**Comment by nelsonjchen** [comment]
Grrrr, I could have a to-do to check this periodically, how did I miss that? I'll get resolved. Also need to make sure this setup will be compatible with modern GitHub pages too and the legacy pages sunset.

**Comment by nelsonjchen** [comment]
I think the link I had in my to-do didn't go into the workflow itself so it disabled.

**Comment by nelsonjchen** [comment]
Hmm, it was going to remind me sunday. I guess I'll make it more often.
